[phases.setup]
nixPkgs = ['nodejs_20', 'openssl', 'python3']

[phases.install]
cmds = ['npm ci --include=dev']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'node .next/standalone/server.js'
