[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['npm install']

[phases.prerender]
cmds = ['npx prisma generate']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm run start'
